version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      nuxt:
        patterns: ["nuxt", "@nuxt/*", "nuxt-*", "@nuxtjs/*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
