baseURL = "/"
assetDir = "/static/"
languageCode = "en-gb"
theme = "hyde-hyde"
title = "craigpeters dot me"
googleAnalytics = "UA-117534850-1"

[params]
    author = "Craig Peters"
    description = "The Blag of Craig Peters"
    authorimage = "/title-starbucks.gif"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    themeColor = "theme-base-08"
    layoutReverse = true
    mainsections = ["posts"]

## Social Accounts
[params.social]
    github = "craigmpeters"
    linkedin = "craigmpeters"
    discord = "283708674357198853"
    email = "craig@craigpeters.me"
    flickr = "craigmpeters"


## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Images"
    weight = "250"
    identifier ="images"
    url="/images/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
[[menu.main]]
    name = "Subscribe to Newsletter"
    identifier = "subscribe"
    weight = 400
    url = "/newsletter/"