baseURL = "/"
languageCode = "en-gb"
theme = "hyde-hyde"
title = "craigpeters dot me"
googleAnalytics = "UA-117534850-1"

[params]
    author = "Craig Peters"
    description = "The Blag of Craig Peters"
    authorimage = "/title-starbucks.gif"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    GraphCommentId = "craigpeters-me"
    themeColor = "theme-base-08"
    layoutReverse = true

## Social Accounts
[params.social]
    github = "craigmpeters"
    instagram = "craigmpeters"
    linkedin = "craigmpeters"
    twitter = "craigmpeters"
    email = "craig@craigpeters.me"


## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
[[menu.main]]
    name = "Subscribe to Newsletter"
    identifier = "subscribe"
    weight = 400
    url = "/newsletter/"